library(tidyr)
library(ggplot2)
a<-read.table("/Users/hilynano/Dropbox/Sim_clade_paper/sim_Y\ paper/plot/Y_component_sim_for_plot",header=T)
tidy_a<- gather(a, location, density, -TE)
tidy_a$TE <- factor(tidy_a$TE, levels = rev(unique(as.character(tidy_a$TE))))
tidy_a$location <- factor(tidy_a$location, levels=c("Dmel_Y","Dmau_Y","Dsim_Y","Dsech_Y"))
tidy_a$density=round(log10(tidy_a$density),2)
P<-ggplot(tidy_a, aes(location,TE)) + geom_tile(aes(fill = density))+ scale_fill_gradient(low ="white", high = "blue",breaks=seq(-4,0,0.5), labels=c("1e-4","1e-3.5","1e-3","1e-2.5","1e-2","1e-1.5","1e-1","1e-0.5","1e-1"))+   scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0)) 
ggsave("/Users/hilynano/Dropbox/Sim_clade_paper/sim_Y\ paper/plot/compositions.pdf",P,width = 6, height = 9,device = "pdf")
